### ISSUE TITLE
Blog theme integration

### ISSUE THREAD

**Issue by jongalloway** [dotnet/dotnetfoundation-website#7]
I added some Blog views to allow customizing layout, removing widgets from the right side and setting `container` class for Bootstrap rendering. Is this necessary?

**Comment by joeaudette** [comment]
in general yes, the approach to customize any view is to copy it locally.

since the only change you made in Index.cshtml and Post.cshtml is adding the container class, I thought maybe I could add that class into the included view if it didn't cause any issue with the bootswatch themes I'm shipping but, it did throw off the layout.

I don't expect those views to change much or often so maintaining local copies shouldn't be a problem. If there are any needed changes for those in future versions I could keep you posted and help update them. Eventually will ship all new views for bootstrap4 as a separate nuget anyway.

Actually I think we should also include local copies of BlogScriptsPartial.cshtml and BlogStylePartial.cshtml in order to add syntax highlighter for blog posts, I do that on my own sites as well and can set that up if you like.

Actually by having the scripts view locally, an alternative would be to use js to add the extra container class without having to keep Index and Post views locally.  Just depends on which approach appeals to you more.
